version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-type: "semver:non-breaking"
        labels:
          - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
        update-type: "semver:non-breaking"
        labels:
          - "dependencies"
