name: Pull Request Rules

on:
  pull_request:
    types: [opened, labeled]

jobs:
  merge_dependabot:
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'dependencies' &&
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.event.pull_request.commits > 1 &&
      contains(github.event.pull_request.labels.*.name, 'dependencies')
    steps:
      - name: Merge pull request
        uses: peter-evans/merge-pull-request@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: ${{ github.event.pull_request.number }}
